[package]
name = "three_card"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.13"
bevy_ggrs = { version = "0.15", features = ["wasm-bindgen"] }
bevy_matchbox = { version = "0.9", features = ["ggrs"] }
bevy_asset_loader = "0.20"
clap = { version = "4.4", features = ["derive"] }
bevy_roll_safe = "0.2"
bevy_egui = "0.27"
rand = "0.8"
rand_xoshiro = "0.6"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
rustflags = ["--cfg=web_sys_unstable_apis"]

[profile.dev.package."*"]
opt-level = 2

[profile.release]
opt-level = 'z'
lto = "thin"
codegen-units = 1
